### ISSUE TITLE
Error initializing SDK in Cloud Run

### ISSUE THREAD

**Issue by francescov1** [googleapis/cloud-debug-nodejs#1066]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Client

2) Did someone already solve this?
No

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Cloud Run
  - Node.js version: 16.8
  - npm version: 7.21.0
  - `@google-cloud/debug-agent` version: 5.2.8

#### Steps to reproduce

Our code is deployed to Cloud Run. Our index.ts file starts with

```
debugAgent.start({serviceContext: {enableCanary: true}, sourceContext: require('./source-context.json') });
```

immediately after all imports. We are getting the following error on start: `@google-cloud/debug-agent Error processing the sourcemaps. Error: An error occurred while processing the sourcemap filesError: An error occurred while reading the sourcemap file dist/index.js.map: Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer`.

Note that we are using Typescript, is there special config needed? We followed the documentation [here](https://cloud.google.com/debugger/docs/setup/nodejs#cloud-run) and [these docs for auto detecting source code ](https://cloud.google.com/debugger/docs/source-context)

**Comment by mctavish** [comment]
Root cause is https://github.com/mozilla/source-map/issues/432 which hasn't made it into a release yet.

I'm exploring migrating to [trace-mapping](https://github.com/jridgewell/trace-mapping) which doesn't have a wasm dependency and has some other benefits as well.
