### ISSUE TITLE
Transpiled Node.js apps that are sub-directories of the git repository don't work.

### ISSUE THREAD

**Issue by slavakl** [googleapis/cloud-debug-nodejs#391]
Similar to #51 but for transpiled apps.
Scenario:
Git repository with a directory serviceA/ that contains a Node.js app. i.e. 
serviceA/
--lib/
----utils.es6
--app.es6 

Repository is hosted in github. Source code transpiled with babel with source maps.
On a server(docker), it runs from /src folder, /src/serviceA.

When trying to set a breakpoint for app.es6, debugger says that corresponding source file cannot be found.
Breakpoint for utils.es6 "successfully" set on UI, but never hits.

Debugging through the agent shows that:

 - app.es6 cannot be found by findScriptsFuzzy. serviceA/app.es6 that comes from request doesn't match with /app.es6

 - serviceA/lib/utils.es6 cannot be found in source map's sources (sourcemapper.mappingInfo) as the relative path it's looking for is not resolved correctly.

It would be great if we could specify "rootFolder" that agent would use to search for sources and maps but also resolve all the relatives paths against, instead of using working directory. That would allow to use an agent with monorepos.

**Comment by DominicKramer** [comment]
@slavakl Thank you for the feedback and sorry for the late reply.  We'll look into this and will let you know what we find.  In the meantime, have you tried the `appPathRelativeToRepository` option:
```
The path within your repository to the directory
containing the package.json for your deployed application. This should
be provided if your deployed application appears as a subdirectory of
your repository. Usually this is unnecessary, but may be useful in
cases where the debug agent is unable to resolve breakpoint locations
unambiguously.
```
It is used as follows:
```js
require('@google-cloud/debug-agent').start({
  appPathRelativeToRepository: 'some/path/'
});
```
It will be helpful to learn how this does or does not help with your problem so we can come up with a solution.  Thanks.

**Comment by slavakl** [comment]
@DominicKramer thank you for the response. I'll try it later today. Seems that I overlooked this options. I tried to set wokingDir but it didn't help. Will report back whether appPathRelativeToRepository solves the problem.

**Comment by slavakl** [comment]
I'm not sure if I set appPathRelativeToRepository right, but did't work in my case. Below is the log file plus some debug output that I added to the agent:

When running with only appPathRelativeToRepository set: 
```
require('@google-cloud/debug-agent').start({
   allowExpressions: true,
  appPathRelativeToRepository: 'serviceA',
  logLevel: 4,
});
MacBook-Pro-3:serviceA slavak$ node serverA.js 
SourceMapper.create: Loaded maps(mapper.infoMap):
	Key: serverA.es6 Map:
		outputFile: serverA.js
		mapFile: serverA.js.map
		mapConsumer._sources: serverA.es6
		mapConsumer._absoluteSources: serverA.es6
	Key: lib/utils.es6 Map:
		outputFile: lib/utils.js
		mapFile: lib/utils.js.map
		mapConsumer._sources: utils.es6
		mapConsumer._absoluteSources: utils.es6

INFO:@google-cloud/debug-agent: activating v8 breakpoint listener (permanent)
INFO:@google-cloud/debug-agent: Unique ID for this Application: SHA1-086bd3b7aafdefbf8409ade8c4265707a563c6b1
DEBUG:@google-cloud/debug-agent: Starting debuggee, project projectx-env
INFO:@google-cloud/debug-agent: Registered as debuggee: gcp:71395596493:261fbb1f587e93fb
INFO:@google-cloud/debug-agent: Fetching breakpoints
INFO:@google-cloud/debug-agent: 	200 completed.
INFO:@google-cloud/debug-agent: Server breakpoints: breakpoint id: 5633d457df04b-ef87-968d8,
	location: { path: 'serviceA/lib/utils.es6', line: 5 }
V8DebugApi.prototype.set. breakpoint.location =  { path: 'serviceA/lib/utils.es6', line: 5 }
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/lib/utils.es6
	calling findScriptsFuzzy
		Found map info
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/lib/utils.es6
	calling findScriptsFuzzy
		Found map info
V8DebugApi.prototype.setInternal. Parameters:
	breakpoint { id: '5633d457df04b-ef87-968d8',
  location: { path: 'serviceA/lib/utils.es6', line: 5 },
  createTime: '2018-01-20T23:08:13.001Z',
  userEmail: 'zzz@zzz.com' }
	mapInfo { file: 'lib/utils.js', line: -1, column: undefined }
	 Scripts found: 
INFO:@google-cloud/debug-agent: 	updating breakpoint data on server 5633d457df04b-ef87-968d8
INFO:@google-cloud/debug-agent: 	deleted breakpoint 5633d457df04b-ef87-968d8
ERROR:@google-cloud/debug-agent: Error: Unable to clear breakpoint in v8
INFO:@google-cloud/debug-agent: Fetching breakpoints
INFO:@google-cloud/debug-agent: 	200 completed.
INFO:@google-cloud/debug-agent: Server breakpoints: breakpoint id: 5633d45eaf9b1-8996-30245,
	location: { path: 'serviceA/serverA.es6', line: 20 }
V8DebugApi.prototype.set. breakpoint.location =  { path: 'serviceA/serverA.es6', line: 20 }
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/serverA.es6
	calling findScriptsFuzzy
		Couldn't find map info
INFO:@google-cloud/debug-agent: 	updating breakpoint data on server 5633d45eaf9b1-8996-30245
INFO:@google-cloud/debug-agent: 	deleted breakpoint 5633d45eaf9b1-8996-30245
ERROR:@google-cloud/debug-agent: Error: Unable to clear breakpoint in v8
```

When running with appPathRelativeToRepository and workingDir set
```
require('@google-cloud/debug-agent').start({
  workingDirectory: "/src",
  allowExpressions: true,
  appPathRelativeToRepository: 'serviceA',
  logLevel: 4,
});

SourceMapper.create: Loaded maps(mapper.infoMap):
	Key: serverA.es6 Map:
		outputFile: serverA.js
		mapFile: serverA.js.map
		mapConsumer._sources: serverA.es6
		mapConsumer._absoluteSources: serverA.es6

	Key: /src/serviceB/serverB.es6 Map:
		outputFile: /src/serviceB/serverB.js
		mapFile: /src/serviceB/serverB.js.map
		mapConsumer._sources: serverB.es6
		mapConsumer._absoluteSources: serverB.es6

	Key: lib/utils.es6 Map:
		outputFile: lib/utils.js
		mapFile: lib/utils.js.map
		mapConsumer._sources: utils.es6
		mapConsumer._absoluteSources: utils.es6

	Key: /src/sharedA/index.es6 Map:
		outputFile: /src/sharedA/index.js
		mapFile: /src/sharedA/index.js.map
		mapConsumer._sources: index.es6
		mapConsumer._absoluteSources: index.es6

INFO:@google-cloud/debug-agent: activating v8 breakpoint listener (permanent)
INFO:@google-cloud/debug-agent: Unique ID for this Application: SHA1-d88c7183d83d82d6b402328e9e8273f71418072c
DEBUG:@google-cloud/debug-agent: Starting debuggee, project projectx-env
INFO:@google-cloud/debug-agent: Registered as debuggee: gcp:71395596493:4e3e2712a7eb6c47
INFO:@google-cloud/debug-agent: Fetching breakpoints
INFO:@google-cloud/debug-agent: 	200 completed.
INFO:@google-cloud/debug-agent: Server breakpoints: breakpoint id: 5633d5723cb19-d039-aaef2,
	location: { path: 'serviceA/serverA.es6', line: 20 }
V8DebugApi.prototype.set. breakpoint.location =  { path: 'serviceA/serverA.es6', line: 20 }
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/serverA.es6
	calling findScriptsFuzzy
		Couldn't find map info
INFO:@google-cloud/debug-agent: 	updating breakpoint data on server 5633d5723cb19-d039-aaef2
INFO:@google-cloud/debug-agent: 	deleted breakpoint 5633d5723cb19-d039-aaef2
ERROR:@google-cloud/debug-agent: Error: Unable to clear breakpoint in v8
INFO:@google-cloud/debug-agent: Fetching breakpoints
INFO:@google-cloud/debug-agent: 	200 completed.
INFO:@google-cloud/debug-agent: Server breakpoints: breakpoint id: 5633d578ab4a6-851c-4be6,
	location: { path: 'serviceA/lib/utils.es6', line: 5 }
V8DebugApi.prototype.set. breakpoint.location =  { path: 'serviceA/lib/utils.es6', line: 5 }
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/lib/utils.es6
	calling findScriptsFuzzy
		Found map info
SourceMapper.prototype.getMappingInfo. inpitPath= serviceA/lib/utils.es6
	calling findScriptsFuzzy
		Found map info
V8DebugApi.prototype.setInternal. Parameters:
	breakpoint { id: '5633d578ab4a6-851c-4be6',
  location: { path: 'serviceA/lib/utils.es6', line: 5 },
  createTime: '2018-01-20T23:13:16.001Z',
  userEmail: 'zzz@zzz.com' }
	mapInfo { file: 'lib/utils.js', line: -1, column: undefined }
	 Scripts found: 
INFO:@google-cloud/debug-agent: 	updating breakpoint data on server 5633d578ab4a6-851c-4be6
INFO:@google-cloud/debug-agent: 	deleted breakpoint 5633d578ab4a6-851c-4be6
ERROR:@google-cloud/debug-agent: Error: Unable to clear breakpoint in v8
INFO:@google-cloud/debug-agent: Fetching breakpoints
INFO:@google-cloud/debug-agent: 	200 completed.
INFO:@google-cloud/debug-agent: Server breakpoints: breakpoint id: 5633d585d8d39-8b7f-dc5d6,
	location: { path: 'sharedA/index.es6', line: 3 }
V8DebugApi.prototype.set. breakpoint.location =  { path: 'sharedA/index.es6', line: 3 }
SourceMapper.prototype.getMappingInfo. inpitPath= sharedA/index.es6
	calling findScriptsFuzzy
		Found map info
SourceMapper.prototype.getMappingInfo. inpitPath= sharedA/index.es6
	calling findScriptsFuzzy
		Found map info
V8DebugApi.prototype.setInternal. Parameters:
	breakpoint { id: '5633d585d8d39-8b7f-dc5d6',
  location: { path: 'sharedA/index.es6', line: 3 },
  createTime: '2018-01-20T23:13:30.001Z',
  userEmail: 'zzz@zzz.com' }
	mapInfo { file: '/src/sharedA/index.js', line: -1, column: undefined }
	 Scripts found: /src/sharedA/index.js
INFO:@google-cloud/debug-agent: 	successfully added breakpoint  5633d585d8d39-8b7f-dc5d6
```
In last case when it said that `successfully added breakpoint` in never hit,  most likely because source was not found in source map.

**Comment by slavakl** [comment]
@DominicKramer do you have any ETA for this?

**Comment by DominicKramer** [comment]
@slavakl I expect this to be resolved within a week.  I will let you know of any updates.  Thanks.

**Comment by DominicKramer** [comment]
Hi.  Sorry for not having a fix for this yet, but I am still investigating it.  I will let you know when I have a solution and/or a workaround.  Thanks.

**Comment by DominicKramer** [comment]
I have a potential solution at PR #402.  Before landing it, I need to make sure it maintains the current behavior of the `appPathRelativeToRepository` config option.

However, if you want, you can test it out now to see if it solves your problem.

Use the following to install the debug agent with the fix:
```
npm install --save https://github.com/DominicKramer/cloud-debug-nodejs.git#fix/transpiled-sub-dirs
```
Then set the `appPathRelativeToRepository` config option to the directory containing the node app.  If I understand correctly, for your app, the value of `appPathRelativeToRepository` should be `serviceA`.

**Comment by slavakl** [comment]
Hi @DominicKramer,

Sorry, missed the notification. Will test later today and let you know.

**Comment by slavakl** [comment]
I checked on my repository today. Everything inside serviceA folder works great. Breakpoints hit, data is captured.
However, if I try to debug a shared module that sits on a root level in repo (sharedA in repo, /src/sharedA on a disk) and used by serviceA, breakpoint is set but never hits. 

Specifically, with configuration
require('@google-cloud/debug-agent').start({
  workingDirectory: "/src",      
  allowExpressions: true,
  appPathRelativeToRepository: 'serviceA',
  logLevel: 4,
});
if set a breakpoint in /src/sharedA/index.js that is used by /src/serviceA/index.js, breakpoint doesn't hit.
I didn't dig deep, but noticed that method V8DebugApi.prototype.setInternal has mapInfo for this breakpoint as follows:
{ file: 'serviceA/src/sharedA/index.js',
  line: -1,
  column: undefined }
I guess path to file is not resolved correctly in this case.

**Comment by DominicKramer** [comment]
Thanks for the feedback.  I will look into this more, and I'll let you know of any updates.  Thanks.

**Comment by DominicKramer** [comment]
Hi, unfortunately I don't have any updates at this time, and I'm still looking into this.  I should be able to have more information within the next week.

**Comment by DominicKramer** [comment]
@slavakl I have a test setup that has the following structure:
```
project-root/
. package.json
. server.js
- subdir1/
  . package.json
  . index.js
- subdir2/
  . package.json
  . index.js
```
Further, I required the debug agent as follows in the `project-root/server.js` file:
```js
require('@google-cloud/debug-agent').start({
  allowExpressions: true,
  appPathRelativeToRepository: '.'
});
```
and started the application from the `project-root` directory.

With this setup, I was able to successfully set and hit breakpoints in each of the `project-root/server.js`, `project-root/subdir1/index.js`, and `project-root/subdir2/index.js` files.

I was wondering how this setup differs from the layout of your code where you were not able to hit breakpoints.

Thanks.

**Comment by slavakl** [comment]
@DominicKramer yes, it works in this case. Mine is a bit different.
repo-root/
- serviceA/
    . package.json
    . index.js
    - lib/
         . lib.js
- serviceB/
    . package.json
    . index.js
    - lib/
         . lib.js
- shared/
    - sharedA/
       . package.json
       . index.js
    - sharedB/
       . package.json
       . index.js

ServiceA and ServiceB are too independent node.js application hosted in the same monorepo. The execution starts either from ServiceA or ServiceB folder.

**Comment by xp500** [comment]
@DominicKramer Is there an ETA for this? I'm running the version you published earlier but it's falling behind from the new code in `master` :(

**Comment by xp500** [comment]
@DominicKramer I've set up the debugger in our production servers but when the breakpoint hits I get the following error:  `Error trying to capture snapshot data: TypeError: Cannot read property 'indexOf' of undefined`

The full stack trace is 
```
Error trying to capture snapshot data: TypeError: Cannot read property 'indexOf' of undefinedTypeError: Cannot read property 'indexOf' of undefined at StateResolver.isPathInCurrentWorkingDirectory_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:301:17
 at StateResolver.shouldFrameBeResolved_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:262:15
 at StateResolver.resolveFrames_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:248:16
 at StateResolver.capture_ (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:172:25
 at Object.capture (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/state/legacy-state.ts:569:8
 at V8DebugApi.captureBreakpointData (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:458:30
 at V8DebugApi.onBreakpointHit (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:384:12
 at eventData.breakPointsHit.forEach.hit (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:83:41
 at V8DebugApi.handleDebugEvents (/usr/hero/code/rest/node_modules/@google-cloud/debug-agent/src/agent/v8/legacy-debugapi.ts:79:44
```

Any idea of what could be going wrong? Running the same code locally works perfectly

**Comment by DominicKramer** [comment]
Sorry for the late reply, but I was out of the office for the last two weeks due to an event out of my control.  I have rebased PR #402 with master so that you can use that if you want.

I wanted to have a release out containing this fix already, but since I was out of the office that was delayed, and I hope to have a release out by next week.

As for your second comment, I am not sure what could be causing the issue.  At first glance though, it doesn't look like it is related to the issue in this thread.  As such, I opened issue #457 for it.

**Comment by dylanscott** [comment]
I'm working on a fairly complex Node app and am also running into issues getting the agent to resolve source files to transpiled files inside of the containers where the application runs. In my case the application is composed of many sub-modules (each with their own `package.json`) which depend on one another, so `appPathRelativeToRepository` may not be sufficient.

In general it seems difficult to anticipate all of the ways an app's source files will map to the running application. I think it could be nice to have an "escape hatch" type of config where we can supply a function that does the path mapping for the debug agent. I'd be happy to open a PR if that's something you'd consider.

**Comment by ofrobots** [comment]
@dylanscott that sounds like a great idea, +1 on a PR (that you already opened, awesome!). At the same time I think it is fair to the module to detect more scenarios without having to resort to the escape hatch of user proving a function to do resolution. I think advanced users will be able to make this work, but in general, getting this right would still requires some 'debugging' which may make it too complex a solution for most users.

Can you provide more details on your deployment setup:
* where are you deploying to? e.g. GAE, etc.
* what does the directory structure look like in the deployed environment. Do you deploy the entire "mono-repo" root directory with all the sub-modules?
* In the Debugger UI, which source mechanism are you using? Local files, vs. GitHub connection etc.
* In the Debugger UI, do you load the root of the directory or individual sub-modules? If you can give a screenshot of the file-browser section of the debugger UI, that might make it very concrete.

**Comment by dylanscott** [comment]
Sure thing!

* We're deploying to Google Kubernetes Engine
* In the debugger UI we're using a GitHub connection, and loading the root of the repository.
* The containers do include the entire mono-repo root directory with all the sub-modules. We use a tool like [lerna](https://github.com/lerna/lerna) to manage building and linking these modules, so inside the container the structure looks something like:

```
├── packages
│   ├── a-shared-module
│   │   ├── package.json
│   ├── service-1
│   │   ├── package.json
│   │   ├── node_modules
│   │   │   ├── a-shared-module (this is a symlink)
│   ├── service-2
│   │   ├── package.json
│   │   ├── node_modules
│   │   │   ├── a-shared-module (this is a symlink)
```

In reality there are a lot of shared modules with multiple layers of dependencies between them. Also for a given service we will only actually build that service's "entrypoint module" and all of its transitive dependencies (though I don't think that's super important to this problem).

**Comment by DominicKramer** [comment]
@slavakl, @dylanscott, and @xp500 because there is a lot of different ways a project can be structured, I have updated the great idea @dylanscott had in their PR #461 to allow for flexibility to handle different project structures.  Please let me know if you are able to use this new approach and if you have any problems or feedback.  Thanks.

**Comment by dylanscott** [comment]
@DominicKramer that looks great, thanks for updating the PR!

**Comment by DominicKramer** [comment]
@dylanscott No problem.  Thanks for contributing the PR.

**Comment by xp500** [comment]
Hi @DominicKramer sorry for the late response! The PR looks great! I'll try it once it gets merged and released...I was having other problems getting the node debugger to work, so I doubt my setup will work with that pr alone, but I'll give it a try anyways.

Is there any ETA for that pr to get released?

Thanks!

**Comment by dinvlad** [comment]
Could you let us know if a release is happening soon?

**Comment by DominicKramer** [comment]
I am working out some issues with the system tests.  Once that is resolved, we will be making a release.

**Comment by DominicKramer** [comment]
Version 3.0.0 has been released that includes the `pathResolver` configuration option.  Documentation for it can be found in `config.ts`.
https://github.com/googleapis/cloud-debug-nodejs/blob/b6b50ba10b17794e11c4c15188ce489287b152a3/src/agent/config.ts#L215
