### ISSUE TITLE
Ability to disambiguate files in Node.js debugger

### ISSUE THREAD

**Issue by sgp** [googleapis/cloud-debug-nodejs#453]
[Originally posted in the Google Issue Tracker.](https://issuetracker.google.com/issues/110745326)

Currently, if the source code has two files named `app.js`--one at `/`, and one at another path, you cannot set up a snapshot in either file because it will say that there are "multiple files with that name". Only workaround is to change the source code to rename one of the conflicting files.

Ideally, one could choose between `/app.js` and `/some/other/file/app.js` when creating the snapshot.

**Comment by ofrobots** [comment]
Hi @sgp. There is a config option that might help here [appPathRelativeToRepository](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/493796f47d648d07a1d245c6dcafd92d357ea1ce/src/agent/config.ts#L86-L94). Can you try with that to see if that helps?

**Comment by sgp** [comment]
@ofrobots - I can try that but what value should I use? `/`?

Here are the paths to the conflicting `app.js` files:

```sh
$ find . -name app.js
./lib/uiToDevice/app.js
./app.js
```

One thing to note: changing the file in `lib/uiToDevice` to `app-somethingelse.js` works around this with no configuration changes.

**Comment by ofrobots** [comment]
@sgp sorry for the late response. You're right that `appPathRelativeToRepository` doesn't necessarily help in your case. There is a new [`pathResolver`](https://github.com/googleapis/cloud-debug-nodejs/blob/b5dc8fbd6f57d29b906c9ccff8cb9eb1fc329626/src/agent/config.ts#L168) configuration option that should help though.

I think something like this should work:

```ts
require('@google-cloud/debug-agent').start({
  pathResolver: scriptPath => [path.join(__dirname, scriptPath)]
});
```

**Comment by ofrobots** [comment]
I'm going to close this issue out. Please leave a comment if you still have issues.
