### ISSUE TITLE
Make log function customizable

### ISSUE THREAD

**Issue by kilianc** [googleapis/cloud-debug-nodejs#458]
Hello 👋🏼

In some cases (multi-cloud deployments) logs are aggregated through a 3rd party service or they need to go through a client library to be streamed.

It would be nice to replace `logpoint()` with something at configuration time like this:

```js
require('@google-cloud/debug-agent').start({
  logFunction: (message) => myRemoteLogger.debug({ txt: message, foo: 'bar' })
})
```

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  I think this is a really good idea and would be really useful.  We'll need to investigate how we can do this, and we'll keep this thread updated.  Thanks.

**Comment by ofrobots** [comment]
Fix on https://github.com/googleapis/cloud-debug-nodejs/issues/458
