### ISSUE TITLE
Design consistent representation of Stackdriver variables

### ISSUE THREAD

**Issue by eyqs** [googleapis/cloud-debug-nodejs#504]
The [Stackdriver Debugger to Chrome DevTools proxy](https://github.com/GoogleCloudPlatform/cloud-debug-proxy-chrome-devtools) currently relies on manually parsing the string in the `value` property of [Stackdriver variables](https://cloud.google.com/debugger/api/reference/rest/v2/debugger.debuggees.breakpoints#Variable). This variable is created in [resolveVariable_](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/src/agent/state/inspector-state.ts), which does not take advantage of the new `type` property of Stackdriver variables. Furthermore, the string `value` is completely different on Node 8 and Node 10 due to changes in the inspector.

It would be nice to design a consistent representation of Stackdriver variables, which uses the `type` property and behaves the same in many versions of Node. Some points to decide would be:
- What should the `value` property be, for structured types such as arrays, maps, and sets? Should they display the length of the array?
- What should the `type` property be? Should they be the strings returned by `typeof`? Should they be the special subtypes according to the [DevTools protocol](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#type-RemoteObject)? Should they be name of the class?
- Should arrays be represented in a special way, compared to objects with numeric keys?
- Which versions of Node should behave the same? What about the other versions?

**Comment by ofrobots** [comment]
This is presently not actionable in this repo. We can take this up with the Debug (UI &Service) and IDE integration team.
