### ISSUE TITLE
nock test failures on master

### ISSUE THREAD

**Issue by fhinkel** [googleapis/cloud-debug-nodejs#512]
`npm test` shows `nock` failures, tests pass overall. See e.g., https://circleci.com/gh/GoogleCloudPlatform/cloud-debug-nodejs/70

```
message: 'Nock: Not allow net connect for "clouddebugger.googleapis.com13:443/v2/controller/debuggees/bar/breakpoints?successOnTimeout=true"' }
Some name Failed to re-register debuggee fake-project: Error: Debuglet not running
```

Anybody wants to look into which mocks are missing?

**Comment by DominicKramer** [comment]
Thanks for opening the issue.  We'll look into it.

**Comment by ofrobots** [comment]
What's the status of this? Is this still relevant?

**Comment by JustinBeckwith** [comment]
Pretty sure this is green now.  Going to just close it out :)
