### ISSUE TITLE
Can't dive into object properties for objects with circular references in Node 10+

### ISSUE THREAD

**Issue by kjin** [googleapis/cloud-debug-nodejs#516]
Objects with circular references aren't being properly represented in Node 10+.

#524 fixes this, but problems with circular references will only disappear once a change to the V8 Inspector Protocol lands in Node 10: because the Inspector API only sends mirror objects and corresponding IDs as a result of communicating over a TCP connection (as opposed to the legacy debugging API, which runs completely in-process), there isn’t a straightforward way to detect circular references. The current behavior is that the variable table being sent through to the Stackdriver Debugger server is filled up to the brim with a breadth-first crawl of an object, or an infinite loop if `capture.maxDataSize` is set to 0.

#### Environment details

  - OS: macOS (irrelevant)
  - Node.js version: 10.8.0
  - npm version: ~6 (irrelevant)
  - `@google-cloud/debug-agent` version: 2.6.0

#### Steps to reproduce

  1. Run `test/test-circular.ts`, with the line to skip the test for Node 10+ removed.

**Comment by kjin** [comment]
The patch doesn't work.

**Comment by kjin** [comment]
The previous comment referred to that I tried a fix in #515 but it doesn't work, so I reverted it. So currently, the #515 fixes don't affect Node 10+.

The actual fix requires a (pending) change in Node 10 itself.

**Comment by ofrobots** [comment]
No reason to keep this bug open given that the PR (blocked on a node release) is already in flight.
