### ISSUE TITLE
sourceContext typings are incorrect

### ISSUE THREAD

**Issue by inversion** [googleapis/cloud-debug-nodejs#541]
The typings for the `sourceContext` config appear to be incorrect.

```
sourceContext: {
 url: 'mygiturl',
 revisionId: 'abc',
}
```
➡️ `Error: Invalid JSON payload received. Unknown name "url" at 'debuggee.source_contexts[0]': Cannot find field.` in stackdriver logs

```
sourceContext: { 
git: {
 url: 'mygiturl',
 revisionId: 'abc',
}
}
```
➡️ works as expected

I'm presuming these nested objects are going to be required for the other source context options too?

Source: https://github.com/googleapis/cloud-debug-nodejs/blob/d0b0363609f36f33b07a236359cdc6c2d5b12614/src/agent/config.ts#L154

**Comment by DominicKramer** [comment]
Thank you for letting us know about this.  Yes, it looks like the typings are incorrect.
