### ISSUE TITLE
Move samples to this repo

### ISSUE THREAD

**Issue by fhinkel** [googleapis/cloud-debug-nodejs#577]
Hi there, our docs-samples repo still have some [debugger samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/debugger). For Node.js, all samples live with their client library if they have one. Can you move the samples over please. Thanks! cc @ofrobots

**Comment by DominicKramer** [comment]
After the samples have been added to this directory, should they be deleted from the `nodejs-docs-samples` repo?

**Comment by fhinkel** [comment]
Yes, I already have PRs open for this: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/832

**Comment by DominicKramer** [comment]
I haven't got a chance to work on this.  I have this as a lower priority and may not get to it until the start of the new year.  If you think it needs to be addressed sooner, let me know.

**Comment by fhinkel** [comment]
Q1 is fine, just want to make sure it's getting done. Thanks!
