### ISSUE TITLE
failed to re-register debuggee project-id: Error: Could not refresh access token

### ISSUE THREAD

**Issue by VikramTiwari** [googleapis/cloud-debug-nodejs#613]
#### Environment details

  - App Engine Standard `nodejs10`
  - `@google-cloud/debug-agent` version: ^3.0.0

This is happening randomly every few minutes. I can see it in the application logs on stackdriver logging.

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  Are you having any issues setting or having breakpoints hit?

**Comment by VikramTiwari** [comment]
Hey @DominicKramer, no issues. Everything works fine but I just keep getting this in the logs.

**Comment by ofrobots** [comment]
This error is typically due to a transient network connection problem. We do a back-off on the network requests and try again later.

If this is not causing any actual issues other than logs, I am inclined to close this issue. If you disagree, please leave a comment here.
