### ISSUE TITLE
Kokoro cannot find configuration

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/cloud-debug-nodejs#650]
The Kokoro tests running against the master branch are failing with the following error:
```
com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration under /tmp/workspace/workspace/cloud-devrel/client-libraries/nodejs/continuous/googleapis/cloud-debug-nodejs/node8/system-test/src/github/cloud-debug-nodejs/.kokoro/continuous/node8
```
However, the debug agent does have a `.kokoro/continuous/node8` directory with configuration files.

Determine how to get the tests on the master branch to run and pass.

**Comment by DominicKramer** [comment]
@JustinBeckwith Would you mind looking into this since it looks like it could be an issue with the kokoro config not exactly aligning with what is expected?  Thanks.

**Comment by JustinBeckwith** [comment]
👋 hey @jkwlui any idea what's up here?

**Comment by jkwlui** [comment]
Sorry about that. Looks like the backend configs for when we switched to running on node10 wasn't updated for cloud-debug-nodejs.

**Comment by JustinBeckwith** [comment]
Pretty sure this was fixed :)
