### ISSUE TITLE
Doesn't work with PM2 on Compute Engine

### ISSUE THREAD

**Issue by MattGson** [googleapis/cloud-debug-nodejs#658]
#### Environment details

  - OS: Ubuntu 16
  - Node.js version: 8
  - npm version: 6
  - `@google-cloud/debug-agent` version: ^3.1.0

#### Steps to reproduce

  1. Install debug client
`require('@google-cloud/debug-agent').start({
    allowExpressions: true,
    serviceContext: {
        service: config.get('service'),
        version: config.get('version')
    },
    projectId: 'my-project'
});`
  2. Run `pm2 start myserverconfig.json`
  3. Error reporting and logging (Winston) work fine.
  4. Snapshots and log-points don't do anything
  4. Service and version show up in other consoles but not in debug console
  5. Run `node server.js` instead of using pm2
  6. Version and service show up in debug console
  7. logpoints and snapshots work as expected.

**Comment by DominicKramer** [comment]
Thank you for letting us know about this.  For clarity, when visiting the Debug console in the Google Cloud Console UI, you don't even see your service or version appear at all to select if and only if you are using `pm2` (i.e. when you are using`node` they do appear)?

**Comment by MattGson** [comment]
That is correct. If I run the application using `node` then the configured version and service will display and I can choose from source repositories. This includes if I run locally and set NODE_ENV=production. I also can use the debugging tools without issue.

When running from pm2, the service and version show up in Stackdriver Logs Viewer as well as in the Error Reporting console. This is all connected through the node winston Stackdriver library and works as expected. The debug console however, does not show the version or service as an option if I run with pm2. This is particularly strange as the Error Reporting console correctly identifies the file where an error occurred. When I click this it links to the Debug console but the version from the Error Reporting console is not there.

PM2 is configured using an environment file and executed from a different path than source of the application.

**Comment by MattGson** [comment]
Update:
Just tested running with `node` from the same directory that I run pm2 from and got the following message in the console:
`@google-cloud/debug-agent No package.json located in working directory.`

This also caused the debug console to stop working.

**Comment by DominicKramer** [comment]
Thanks for the info.  It looks like the debug agent is looking for the application source in the current working directory, but cannot find it because `pm2` is running elsewhere.  I suggest using the [`workingDirectory`](https://github.com/googleapis/cloud-debug-nodejs/blob/d97c5adfe750028ec3c6cbb3e4df370006630b8e/src/agent/config.ts#L86) configuration option to explicitly specify which directory contains the application's `package.json` file.  Let me know if that does or does not solve the problem.

**Comment by MattGson** [comment]
Hey, that has worked. Thanks for your help!

**Comment by DominicKramer** [comment]
Glad to be of help.
