### ISSUE TITLE
Security vulnerability in 2 deps

### ISSUE THREAD

**Issue by hrasadi** [googleapis/cloud-debug-nodejs#670]
According to `npm audit`, these three packages are vulnerable:

* nyc > istanbul-reports > handlebat (fixed in nyc@14.0.0)
* mocha > js-yaml (fixed in js-yaml>=3.13.1)

**Comment by JustinBeckwith** [comment]
Thanks! These are both dev dependencies, so should have no downstream effect on the installed npm module.  As these get fixed in our downstream dependencies, it should be solved.
