### ISSUE TITLE
Windows tests do not pass in CI for Node 10

### ISSUE THREAD

**Issue by bcoe** [googleapis/cloud-debug-nodejs#686]
#### Environment details

  - OS: Windows
  - Node.js version: Node 10
  - npm version: 6.9.0
  - `@google-cloud/debug-agent` version:

#### Steps to reproduce

  1. use the up-to-date `test.bat` in synthtool repo.
  2. kick off unit tests.

**Comment by DominicKramer** [comment]
@bcoe Do you have an update on this?  Thanks

**Comment by bcoe** [comment]
looks like Windows tests are passing now :+1:

**Comment by kjin** [comment]
@bcoe Can this be removed now? https://github.com/googleapis/cloud-debug-nodejs/blob/6d809e637f06996b9b6e76acf105a695f3964512/synth.py#L22-L26

**Comment by bcoe** [comment]
@kjin give removing it a shot :+1: this might be from when we were debugging the container (I hope).
