### ISSUE TITLE
Use `teeny-request` instead of `request`

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/cloud-debug-nodejs#749]
The `teeny-request` module can be used instead of `request` to improve require speed of the debug agent.

**Comment by kjin** [comment]
I'm pretty sure this library already uses `teeny-request`, all you need to do is remove two references to `request` types.

**Comment by DominicKramer** [comment]
My local code was on the branch `chore/update-teeny-request` that was out of date while the `chore/update-teeny-request-5` was the correct branch that was up-to-date with master.  I have PR #750 to resolve this issue.
