### ISSUE TITLE
Unable to fetch breakpoints – stopping fetcher 

### ISSUE THREAD

**Issue by REPTILEHAUS** [googleapis/cloud-debug-nodejs#761]
Running a NodeJS app on GAE with v.4.0.0 of ```@google-cloud/debug-agent``` and I keep seeing this error popping up every few days

Potentially related to this bug https://github.com/googleapis/cloud-debug-nodejs/issues/405 however the fix suggests upgrading to v2 (being on v4 its not applicable to my situation).

```
@google-cloud/debug-agent Unable to fetch breakpoints – stopping fetcher { FetchError: network timeout at: https://clouddebugger.googleapis.com/v2/controller/debuggees/gcp%3A323540892590%3Aa119073f04de5462/breakpoints?successOnTimeout=true
```

I have a valid API key specified in my applications env

**Comment by DominicKramer** [comment]
Thanks for the feedback.  Are you seeing this message appear in your logs and your snapshots are not hit, or are you seeing the messages but your snapshots are still working?

**Comment by REPTILEHAUS** [comment]
Im not 100% sure whether my instance is hit nor am I sure if it was down at the time, there is nothing in the logs other than this

**Comment by DominicKramer** [comment]
@REPTILEHAUS thanks for the feedback.  We will need to investigate whether this is an issue or not.  That is, if it is because the instance is turning down or if it a credential issue preventing the debug agent to communicate with the debug API.

**Comment by jakeleventhal** [comment]
I'm getting the sam issue with two different versions of the error

First
```
@google-cloud/debug-agent Unable to fetch breakpoints – stopping fetcher FetchError: request to https://clouddebugger.googleapis.com/v2/controller/debuggees/gcp%myuniqueid%myuniqueid/breakpoints?successOnTimeout=true&waitToken=23ad7c904aa665e3 failed, reason: Client network socket disconnected before secure TLS connection was established
at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1455)
at ClientRequest.emit (events.js:210)
at TLSSocket.socketErrorListener (_http_client.js:406)
at TLSSocket.emit (events.js:210)
at emitErrorNT (internal/streams/destroy.js:91)
at emitErrorAndCloseNT (internal/streams/destroy.js:59)
at processTicksAndRejections (internal/process/task_queues.js:80)
```

Second
```
Stack trace sample
@google-cloud/debug-agent Unable to fetch breakpoints – stopping fetcher FetchError: request to https://clouddebugger.googleapis.com/v2/controller/debuggees/gcp%myuniqueid%myuniqueid/breakpoints?successOnTimeout=true&waitToken=23ad7c904aa665e3 failed, reason: socket hang up
at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1455)
at ClientRequest.emit (events.js:210)
at TLSSocket.socketOnEnd (_http_client.js:440)
at TLSSocket.emit (events.js:215)
at endReadableNT (_stream_readable.js:1183)
at processTicksAndRejections (internal/process/task_queues.js:80)
```

**Comment by DominicKramer** [comment]
I did some investigation, and this error is occurring due to intermittent problems connecting to the debug API.  At the time the log message is printed, the debug agent cannot contact the API, but it initiates a re-registration.  As such, the agent is not stopped.  Instead, breakpoints will be collected again after the registration is complete.
