### ISSUE TITLE
heap limit gets approximately quadrupled just prior to being reached

### ISSUE THREAD

**Issue by eug48** [googleapis/cloud-debug-nodejs#775]
#### Environment details

  - OS: Linux
  - Node.js version: 10 - 13
  - npm version: 6.10.3
  - `@google-cloud/debug-agent` version: 4.0.4

#### Steps to reproduce

  1. Clone `https://github.com/eug48/nodejs-memory-test/` and run `npm install`
  2. Run `./run.sh node:10-alpine enable-cloud-debug` and note how v8.getHeapStatistics().heap_size_limit gets increased prior to OOM
  3. Run `./run.sh node:10-alpine disable-cloud-debug` and note how the above behaviour doesn't occur

It seems like this is due to the V8 Debugger calling `AddNearHeapLimitCallback` (https://github.com/v8/v8/blob/65079f10b9624775c0cff22ae0d30eb25b5a4452/src/inspector/v8-debugger.cc#L125) and then quadrupling the heap limit before triggering a debug break for the OOM. I would guess that the Stackdriver Agent does not handle this unsolicited break and so `RestoreOriginalHeapLimit` does not get called.

**Comment by bcoe** [comment]
@eug48 thank you for the bug report, this doesn't sound right.

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  This looks like it could be a bug in V8 itself, and so I opened a v8 issue at https://bugs.chromium.org/p/chromium/issues/detail?id=1044792.  As such, I am closing this issue.
