### ISSUE TITLE
Use `pack-n-play` for install tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/cloud-debug-nodejs#790]
Over in #789 we moved away from `post-install-test` because it was causing system test failures that were impossible to debug.  We need to fix the underlying issues with the now-renamed project `pack-n-play`, and move back.

**Comment by DominicKramer** [comment]
FYI: I added and removed the rotating_light symbol to test how to use the GitHub [cli](https://cli.github.com/) to list issues with a rotating light.

**Comment by JustinBeckwith** [comment]
eh, we'll get here or we won't 🤷
