### ISSUE TITLE
Release client as GA

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/cloud-debug-nodejs#897]
Package name: @google-cloud/debug
Current release: **beta**
Proposed release: **GA**

I think we should consider taking this module GA.  The checklist we follow is below, but honestly, ownership was the only thing keeping us from GA-ing it previously.  @mctavish and @Louis-Ye now that y'all are picking this up, any objections to bumping the release-level?

## Required

- [x] 28 days elapsed since last beta release with new API surface
- [x] Server API is GA
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

## Optional

- [ ] Most common / important scenarios have descriptive samples
- [ ] Public manual methods have at least one usage sample each (excluding overloads)
- [x] Per-API README includes a full description of the API
- [x] Per-API README contains at least one “getting started” sample using the most common API scenario
- [x] Manual code has been reviewed by API producer
- [x] Manual code has been reviewed by a DPE responsible for samples
- [x] 'Client Libraries' page is added to the product documentation in 'APIs & Reference' section of the product's documentation on Cloud Site

**Comment by JustinBeckwith** [comment]
FYI @bcoe @danoscarmike

**Comment by mctavish** [comment]
No objections here.  I believe that this package has effectively been GA for some time and now that the ownership is firmed up I'm happy to see it become official.

**Comment by Louis-Ye** [comment]
No objection for GA.

**Comment by legopin** [comment]
With issue #811 outstanding, I don't think this package is ready for GA.

Unchecked memory leak is not an acceptable behavior in production deployments, which is what cloud debugger was advertised to operate in.

Please continue to look into it before going GA

**Comment by mctavish** [comment]
Agreed; that's the primary reason that this issue hasn't progressed.  It's worth making that explicit in this issue though.
