### ISSUE TITLE
Could not determine the output file associated with the transpiled input file

### ISSUE THREAD

**Issue by beingminimal** [googleapis/cloud-debug-nodejs#932]
### Problem you have encountered:
Receiving "Could not determine the output file associated with the transpiled input file" error when we deploy node js code.

### Configurations:
- typescript - v4.0.3
- node - v14.15.0
- webpack - v5.4.0

We tried to enable sourcemap with below webpack sourcemapers

- 'source-map'
- 'inline-source-map'
- 'hidden-source-map'
But we are not able to set debugger in typescript based project.

### What you expected to happen:
The debugger should be attached to a node js based project which contains code in TS and transpile through webpack.

**Comment by beingminimal** [comment]
@yoshi-automation any update on this?

**Comment by mctavish** [comment]
The current requirements for handling transpiled code is that the sourcemaps are generated and deployed alongside the transpiled code.

Can you provide a rough outline of your file tree and/or build setup?

**Comment by Ahmad-P** [comment]
I got an update:

Hi there,

We tried with deploying our transpiled code along with sourcemaps generated by different devtool options but still receiving same error.

Here is my build files for production in which we tried with below devtool options

'source-map'
'inline-source-map'
'hidden-source-map'
webpack.config.js
{
    mode: 'production',
    devtool: 'source-map',
    entry: {
      main: './src/main.ts',
    },
    output: {
      filename: '[name].bundle.js',
      path: path.resolve( __dirname, 'dist' )
    },
    module: {
      rules: [ {
        test: /\.ts$/i,
        loader: 'ts-loader',
        exclude: [ /node_modules/ ]
      }]
    },
    resolve: {
      extensions: [ '.ts', '.js' ],
      modules: [ 'src', 'node_modules' ]
    },
    devServer: {
      port: 8000,
      historyApiFallback: true,
      writeToDisk: true,
      open: true,
      lazy: false
    },
    optimization: {
      nodeEnv: 'production',
      minimize: true
    },
    plugins: [
      new CleanWebpackPlugin(),
       new webpack.DefinePlugin( { "process.env.NODE_ENV": JSON.stringify( "production" ) } ),
      new TerserPlugin(),
      new webpack.NoEmitOnErrorsPlugin()
      new HtmlWebpackPlugin( { template: "./index.html" } )
    ]
  }

For deployment we are using docker and copying only dist folder in final image.

dockerfile

FROM node:slim
WORKDIR /app
COPY dist /app/dist
COPY index.js .
EXPOSE 8080
ENTRYPOINT [ "node",  "index.js" ]
CMD [ "node","index.js" ]

**Comment by mctavish** [comment]
I don't see anything obviously problematic here.  Can you confirm that the file you're trying to debug is present in the generated sourcemap's sources list?

**Comment by beingminimal** [comment]
Hi @mctavish, 
I have verified from dev tools, files which I am trying to debug are present in the generated source map's source. 
Today I tried to attach debugger again with the same configurations and now I am getting "Unable to set a breakpoint in v8" error in log point and snapshot both.

**Comment by B-0-B-B-Y** [comment]
Any update on this? I have a similar issue: I have a node.js project written in ES6+ which is being transpiled with webpack. The transpiled code, alongside the source-map for every single js file is deployed to app engine. I automatically also generate a source-context.json file, which is deployed as well at the root level. I can change to viewing the source code from the github has as pointed in source-context.json, but when I setup a snapshot on a particular line in a file, nothing happens, even though I can see the logs coming through. Switching back to the deployed code (the ugly transpiled js) I can see the snapshot is logged on the same line as the source code, which is incorrect as the source code line doesn't match the transpiled code line. It's crazy to think we cannot debug code deployed to app engine unless we write it in ES5 or try and find the correct line in the transpiled ugly js file.

**Comment by Louis-Ye** [comment]
There are several fixes related to the sourcemap have been merged in after v5.2.5. 

The v5.2.5+ version of cloud-debug-nodejs has the option to print out the debugging information for the source mapper, which can help to identify the problem further. So if the problem still exists, please attach the debugging information to the thread and reopen the ticket.

Here is the code on how to get the debugging information for the source mapper:
`require('@google-cloud/debug-agent').start({logLevel: 4});`
