### ISSUE TITLE
Support Cloud Run Platform Label

### ISSUE THREAD

**Issue by Louis-Ye** [googleapis/cloud-debug-nodejs#952]
Currently the node.js debugger agent can support the cloud_function label when the application is running on GCF (Cloud Functions). This label will be used at the debugger GCP page to show the non-active debuggees when the they scale to zero on GCF.

The same thing should be done to not just GCF, but Cloud Run as well, because the application on Cloud Run would also scale to zero.

**Comment by mctavish** [comment]
This feature will not be supported prior to archival.
